version: "3.9"
services:
  landing:
    build:
      context: .
      dockerfile: dockerfile
    container_name: landing-tunegocioinmobiliario
    ports:
      - "3013:3000"
    restart: unless-stopped

    networks:
      - intrabuhonet

networks:
  intrabuhonet:
    external: true